# Generated by Django 5.2.1 on 2025-07-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_citamedica_unique_together_citamedica_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='doctor',
        ),
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together={('fecha', 'hora_cita')},
        ),
        migrations.RemoveField(
            model_name='citamedica',
            name='doctor',
        ),
    ]
