# Generated by Django 5.2.1 on 2025-07-02 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_doctor_user'),
        ('doctor', '0003_remove_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioatencion',
            name='doctor',
            field=models.ForeignKey(default=1, help_text='Doctor al que pertenece este horario.', on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to='core.doctor', verbose_name='Doctor'),
            preserve_default=False,
        ),
    ]
